# Generated by Django 4.1.3 on 2022-11-03 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0024_alter_competence_id_alter_education_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='information',
            old_name='facebook',
            new_name='codingamge',
        ),
        migrations.RenameField(
            model_name='information',
            old_name='instagram',
            new_name='kaggle',
        ),
        migrations.RemoveField(
            model_name='information',
            name='twitter',
        ),
        migrations.AlterField(
            model_name='project',
            name='demo',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='github',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='projects/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='tools',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
